### ISSUE TITLE
BUG report: about search result layerout

### ISSUE THREAD

**Issue by flashlab** [geecko86/QuickLyric#139]
When the searching is processing, screen rotating or slide back to the unfinished page will cause app crash. Check the report below.

**screen rotating**
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.geecko.QuickLyric/com.geecko.QuickLyric.SearchActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.access$900(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.geecko.QuickLyric.fragment.SearchFragment.setResults(SearchFragment.java:130)
	at com.geecko.QuickLyric.fragment.SearchFragment.onActivityCreated(SearchFragment.java:76)
	at android.app.Fragment.performActivityCreated(Fragment.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	... 13 more
```

**slide back**
```
java.lang.NullPointerException
	at com.geecko.QuickLyric.fragment.SearchFragment.setResults(SearchFragment.java:130)
	at com.geecko.QuickLyric.fragment.SearchFragment.onActivityCreated(SearchFragment.java:76)
	at android.app.Fragment.performActivityCreated(Fragment.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.BackStackRecord.run(BackStackRecord.java)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java)
	at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
	at android.view.Choreographer.doCallbacks(Choreographer.java)
	at android.view.Choreographer.doFrame(Choreographer.java)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by geecko86** [comment]
Both issues have been fixed, thank you very much for reporting them!
